version: '2'
services:
  web:
    build: ./web
    command: gunicorn --workers=3 site_project.wsgi:application -b 0.0.0.0:8000
    env_file:
      - ./web/.env
    ports:
      - "8000:8000"
    volumes:
      - ./web:/code
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-enabled:/etc/sites-enabled
      - ./web:/code
    links:
      - web
