version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: ./web
    environment:
      PYTHONPATH: '/code'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn site_project.wsgi:application -w 3 -b :8000"
    env_file:
      - ./web/.env
    ports:
      - "8000:8000"
    volumes:
      - ./web:/code
    links:
      - db
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-enabled:/etc/sites-enabled
      - ./web:/code
    links:
      - web
